force-app/main/default/objects/ApplicationLog__c/ApplicationLog__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>LOG #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLog__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error:	Handled and unhandled exceptions that need support team visibility (e.g. A controller class failed to update a record) 

Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings) 

Info: 	Information messages useful to ensure a process is running smoothly (e.g. When a batch job runs how many records were processed?, What was the start time/end time etc) 

Warning:  	Messages that allow developers to notify support teams that application limits set during the design phase might be reached (e.g. A batch job has been set up to process 1000 records at a time. If the number of records pending to be processed exceeds the limit the support team can be notified that the limit may need to be increased due to increasing volumes)</description>
    <inlineHelpText>Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings)</inlineHelpText>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Integration_Payload__c.field-meta.xml
<CustomField>
    <fullName>Integration_Payload__c</fullName>
    <description>If log is integration related show payload</description>
    <inlineHelpText>If log is integration related show payload</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Log_Code__c.field-meta.xml
<CustomField>
    <fullName>Log_Code__c</fullName>
    <description>Either the exception error code of custom org code for record</description>
    <inlineHelpText>Either the exception error code of custom org code for record</inlineHelpText>
    <label>Log Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message to log</description>
    <inlineHelpText>Message to log</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <description>The related record id</description>
    <externalId>true</externalId>
    <inlineHelpText>The related record id</inlineHelpText>
    <label>Reference Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Reference_Info__c.field-meta.xml
<CustomField>
    <fullName>Reference_Info__c</fullName>
    <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
    <inlineHelpText>The related record info (e.g. Apex Batch Job Id, Contact etc)</inlineHelpText>
    <label>Reference Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>The originating class (e.g. ScheduledMonthlyNotificationToProvider)</description>
    <externalId>true</externalId>
    <inlineHelpText>The originating class (e.g. ScheduledMonthlyNotificationToProvider)</inlineHelpText>
    <label>Source</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <description>The originating function in the class (e.g. UpdateDivision() )</description>
    <externalId>true</externalId>
    <inlineHelpText>The originating function in the class (e.g. UpdateDivision() )</inlineHelpText>
    <label>Source Function</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Raw exception stack trace for unhandled errors</description>
    <inlineHelpText>Raw exception stack trace for unhandled errors</inlineHelpText>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Timer__c.field-meta.xml
<CustomField>
    <fullName>Timer__c</fullName>
    <description>The time in milliseconds for the transaction (e.g. For integration/batch apex messages it might be the time taken to process)</description>
    <inlineHelpText>The time in milliseconds for the transaction (e.g. For integration/batch apex messages it might be the time taken to process)</inlineHelpText>
    <label>Timer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GlobalUtility.cls
/*-----------------------------------------------------------------------------------
Description:   A global utility class for common functions
Test Class:    GlobalUtility_Test
-----------------------------------------------------------------------------------*/
public without sharing class GlobalUtility {

    /*-----------------------------------------------------------------------------------
    Description:   Method to create a single application log record
                   logLevel - Debug, Error, Info, Warning
                   sourceClass - Originating trigger or utility class
                   sourceFunction - Method in class above that caused the message
                   referneceId - Process Identifier (e.g. Job Id)
                   referenceInfo - Process information
                   payLoad - Optional based on integration messages
                   ex - the standard exception object for errors
                   timeTaken - The time in milliseconds of the transaction
    Param:         As described in description.
    -----------------------------------------------------------------------------------*/
    public static void logMessage(String logLevel,
                                    String sourceClass,
                                    String sourceFunction,
                                    String referenceId,
                                    String referenceInfo,
                                    String payLoad,
                                    Exception ex,
                                    long timeTaken) {

        ApplicationLogWrapper msg = new ApplicationLogWrapper();
        
        msg.source = sourceClass;
        msg.sourceFunction = sourceFunction;
        msg.referenceId = referenceId;
        msg.referenceInfo = referenceInfo;
        msg.payload = payLoad;
        msg.debugLevel = logLevel;
        msg.ex = ex;
        msg.Timer = timeTaken;
        logMessages(new list <ApplicationLogWrapper> {msg});
    }    

    /*-----------------------------------------------------------------------------------
    Description:   Method to create application log records in salesforce
    Param:         list of ApplicationLogWrapper objets with logging information   
    -----------------------------------------------------------------------------------*/
    public static void logMessages(list <ApplicationLogWrapper> messages) {
        if(messages.size() == 0) return;
        
        list <ApplicationLog__c> logs = new list <ApplicationLog__c>();
        
        for(ApplicationLogWrapper message : messages) {
            ApplicationLog__c applicationLogRecord = new ApplicationLog__c();
        
            applicationLogRecord.Source__c = message.source;
            applicationLogRecord.Source_Function__c = message.sourceFunction;
            applicationLogRecord.Reference_Id__c = message.referenceId;
            applicationLogRecord.Reference_Info__c = message.referenceInfo;
            applicationLogRecord.Integration_Payload__c = message.payload;
        
            if(message.ex != null){
                applicationLogRecord.Stack_Trace__c = message.ex.getStackTraceString();
                applicationLogRecord.Message__c = message.ex.getMessage();
            }
            
            applicationLogRecord.Debug_Level__c = message.debugLevel;
            applicationLogRecord.Log_Code__c = message.logCode;
            applicationLogRecord.Timer__c = message.timer;
            logs.add(applicationLogRecord);
        }

        if(logs.size() > 0)
            insert logs;
    }
    
}